# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created: Fri May 29 11:33:36 2015
#      by: PyQt4-uic 0.2.15 running on PyQt4 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(520, 403)
        AboutDialog.setMinimumSize(QtCore.QSize(520, 0))
        AboutDialog.setMaximumSize(QtCore.QSize(520, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        AboutDialog.setPalette(palette)
        AboutDialog.setAutoFillBackground(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(170, 87, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.widget_pic = QtWidgets.QWidget(AboutDialog)
        self.widget_pic.setObjectName("widget_pic")
        self.horizontalLayout_2.addWidget(self.widget_pic)
        spacerItem1 = QtWidgets.QSpacerItem(170, 87, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(AboutDialog)
        self.label.setMinimumSize(QtCore.QSize(110, 0))
        self.label.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.label_version = QtWidgets.QLabel(AboutDialog)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_3.addWidget(self.label_version)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 23, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.label_3 = QtWidgets.QLabel(AboutDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem7 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout.addItem(spacerItem7)
        self.label_2 = QtWidgets.QLabel(AboutDialog)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_pyqtgraph = QtWidgets.QLabel(AboutDialog)
        self.label_pyqtgraph.setTextFormat(QtCore.Qt.RichText)
        self.label_pyqtgraph.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pyqtgraph.setOpenExternalLinks(True)
        self.label_pyqtgraph.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_pyqtgraph.setObjectName("label_pyqtgraph")
        self.verticalLayout.addWidget(self.label_pyqtgraph)
        self.label_cxfreeze = QtWidgets.QLabel(AboutDialog)
        self.label_cxfreeze.setTextFormat(QtCore.Qt.RichText)
        self.label_cxfreeze.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cxfreeze.setOpenExternalLinks(True)
        self.label_cxfreeze.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_cxfreeze.setObjectName("label_cxfreeze")
        self.verticalLayout.addWidget(self.label_cxfreeze)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.pushButton_close = QtWidgets.QPushButton(AboutDialog)
        self.pushButton_close.setObjectName("pushButton_close")
        self.horizontalLayout.addWidget(self.pushButton_close)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AboutDialog)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        AboutDialog.setWindowTitle(QtWidgets.QApplication.translate("AboutDialog", "About", None))
        self.label.setText(QtWidgets.QApplication.translate("AboutDialog", "Version", None))
        self.label_version.setText(QtWidgets.QApplication.translate("AboutDialog", "TextLabel", None))
        self.label_3.setText(QtWidgets.QApplication.translate("AboutDialog", "TinyRadTool uses:", None))
        self.label_2.setText(QtWidgets.QApplication.translate("AboutDialog", "<html><head/><body><p><a href=\"https://pypi.org/project/PyQt5/\"><span style=\" text-decoration: underline; color:#0000ff;\">https://pypi.org/project/PyQt5//</span></a></p></body></html>", None))
        self.label_pyqtgraph.setText(QtWidgets.QApplication.translate("AboutDialog", "<html><head/><body><p><a href=\"http://www.pyqtgraph.org/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.pyqtgraph.org/</span></a></p></body></html>", None))
        self.label_cxfreeze.setText(QtWidgets.QApplication.translate("AboutDialog", "<html><head/><body><p><a href=\"http://cx-freeze.sourceforge.net/\"><span style=\" text-decoration: underline; color:#0000ff;\">http://cx-freeze.sourceforge.net/</span></a></p></body></html>", None))
        self.pushButton_close.setText(QtWidgets.QApplication.translate("AboutDialog", "Close", None))

